# Generated by Django 6.0 on 2026-03-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms', models.CharField(max_length=200)),
                ('bill_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('vehicle_no', models.CharField(max_length=50)),
                ('consignee_gstin', models.CharField(max_length=20)),
                ('consignor_gstin', models.CharField(max_length=20)),
                ('invoice_no', models.CharField(max_length=50)),
                ('gc_note_no', models.CharField(max_length=50)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('pkg', models.IntegerField()),
                ('particular', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('amount', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(default=9)),
                ('sgst', models.FloatField(default=9)),
                ('grand_total', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
