# Generated by Django 6.0 on 2026-03-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbill',
            name='ms_address1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transportbill',
            name='ms_address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transportbill',
            name='cgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportbill',
            name='sgst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
