# Generated by Django 6.0 on 2026-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_transportbill_ms_address1_transportbill_ms_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbill',
            name='consignee_gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transportbill',
            name='consignor_gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
