# Generated by Django 6.0 on 2026-03-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_transportbill_consignee_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbill',
            name='add_stamp',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='transportbill',
            name='gst_choice',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
